# Application
spring.application.name=wissi-backend
server.port=${PORT:8080}

# Firebase Configuration - Mock Service for production
firebase.enabled=false  # Mock Service
# firebase.enabled=true   # Firebase real (desarrollo local)

# Bean override
spring.main.allow-bean-definition-overriding=true

# File Upload (carpeta temporal en Render)
app.upload.dir=/tmp/imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.springframework=INFO
logging.level.com.wissi=DEBUG
