# Application
spring.application.name=wissi-backend
server.port=${PORT:8080}

# Firebase Configuration
firebase.enabled=true  # Usar Firebase real

# Permitir sobreescritura de Beans
spring.main.allow-bean-definition-overriding=true

# File Upload (carpeta temporal en Render)
app.upload.dir=/tmp/imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.springframework=INFO
logging.level.com.wissi=DEBUG

# Evitar conflictos con commons-logging
logging.level.org.apache.commons.logging=ERROR
logging.config=classpath:logback-spring.xml