# Application
spring.application.name=wissi-backend
server.port=${PORT:8080}

# File Upload (carpeta temporal en Render)
app.upload.dir=/tmp/imagenes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Logging
logging.level.org.springframework=INFO
logging.level.com.wissi=DEBUG
